### ISSUE TITLE
hi bro,do you have any idea about disable BFV proto ssl?

### ISSUE THREAD

**Issue by SoraKasvgano** [zeroKilo/meSSL#1]
hi bro,do you have any idea about disable BFV proto ssl?

emmm
 also 

if we could get other bf1 player's ping offset would be fine, we are working on a free bf1 manage tool

check at bfban.com

**Comment by zeroKilo** [comment]
here some hints 

https://github.com/zeroKilo/BFP4FToolsWV/wiki/SSL-Bypass 

please write me on reddit next time, greetz
